security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    app_user_provider_oauth:
      id: App\Service\Security\PbsUserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api
      stateless: false

      custom_authenticators:
        - App\Service\Security\PbsAuthenticator
      entry_point: App\Service\Security\PbsAuthenticator

      logout:
        path: /logout

    main:
      lazy: true

  # note: use new authenticator system. Remove after upgrading to Symfony 6.2
  enable_authenticator_manager: true

  # Define access control methods for different endpoints
  # oauth endpoint is publicly available
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: "%api_regex%/oauth/v2/code", roles: PUBLIC_ACCESS, methods: [ POST ] }
    - { path: "%api_regex%/groups", roles: IS_AUTHENTICATED_FULLY }
