sentry:
  dsn: "%env(SENTRY_DSN)%"
  options:
    environment: "%env(APP_ENV)%"
    before_send: 'sentry.callback.before_send'
    send_default_pii: true

services:
  sentry.callback.before_send:
    class: 'App\Service\Sentry'
    factory: [ '@App\Service\Sentry', 'sentryFilter' ]
