
# Widget routes
widgets:
  resource: "apps/widgets.yml"
  prefix: /widgets
  name_prefix: widgets_

# QUAP routes
quap:
  resource: "apps/quap.yml"
  prefix: /quap
  name_prefix: quap_

# General routes
general:
  resource: "apps/general.yml"
  prefix: /general
  name_prefix: general_

census:
  resource: "apps/census.yml"
  prefix: /census
  name_prefix: census_
