preview:
  path: /preview
  methods: GET
  controller: App\Controller\Api\Apps\CensusController::getPreview

filter:
  path: /filter
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\FilterController:getGroupTypes
