
sharing:
  path: /share
  methods: GET
  controller: App\Controller\Api\Apps\OverviewController::getOverviewSharing

share:
  path: /share
  methods: POST
  controller: App\Controller\Api\Apps\OverviewController::shareOverview

departments-preview:
  path: /departments/preview
  methods: GET
  controller: App\Controller\Api\Apps\OverviewController::getOverviewOfDepartmentsPreview
