
preview:
  path: /preview
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\MembersGroupController:getPreview

filter:
  path: /filter
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\FilterController:getFilterData

members_gender:
  path: /members-gender
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\MembersGenderController:getDemographicGroupData

members_group:
  path: /members-group
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\MembersGroupController:getGroupMembersData

demographic_camp:
  path: /camps
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\CampController:getDemographicCampData

leader_overview:
  path: /leader-overview
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\LeaderOverviewController:getLeaderOverviewData

members_birthyear:
  path: /age-group-demographic
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\MembersBirthyearController:getMembersBirthyearData

members_entered_left:
  path: /entered-left
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\MembersEnteredLeftController:getEnteredLeftMembersData

geo_location:
  path: /geo-location
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\GeoLocationController::getGeoLocations

role_overview:
  path: /role-overview
  methods: GET
  controller: App\Controller\Api\Apps\Widgets\RoleOverviewController:getRoleOverview

census_table:
  path: /census-table
  methods: GET
  controller: App\Controller\Api\Apps\CensusController::getTableData

census_members:
  path: /census-members
  methods: GET
  controller: App\Controller\Api\Apps\CensusController::getMembersData

census_development:
  path: /census-development
  methods: GET
  controller: App\Controller\Api\Apps\CensusController::getDevelopmentData

census_treemap:
  path: /census-treemap
  methods: GET
  controller: App\Controller\Api\Apps\CensusController::getTreemapData

