<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201026095824 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE hc_demographic_camp_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE hc_invite_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE hc_leader_overview_leader_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE hc_leader_overview_qualification_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE hc_widget_demographic_camp_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE hc_widget_demographic_department_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE hc_widget_demographic_entered_left_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE hc_widget_demographic_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE hc_widget_leader_overview_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_camp_state_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_event_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_event_date_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_event_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_event_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_event_type_qualification_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_group_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_person_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_person_event_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_person_event_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_person_qualification_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_person_role_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_qualification_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_role_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE midata_youth_sport_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE hc_demographic_camp_group (id INT NOT NULL, demographic_camp_id INT NOT NULL, group_id INT DEFAULT NULL, m_count INT DEFAULT NULL, f_count INT DEFAULT NULL, u_count INT DEFAULT NULL, m_count_leader INT DEFAULT NULL, f_count_leader INT DEFAULT NULL, u_count_leader INT DEFAULT NULL, group_type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_58535CE26C5AD790 ON hc_demographic_camp_group (demographic_camp_id)');
        $this->addSql('CREATE INDEX IDX_58535CE2FE54D947 ON hc_demographic_camp_group (group_id)');
        $this->addSql('CREATE INDEX IDX_58535CE2C92EFB06 ON hc_demographic_camp_group (m_count)');
        $this->addSql('CREATE INDEX IDX_58535CE2CB29AFFC ON hc_demographic_camp_group (f_count)');
        $this->addSql('CREATE INDEX IDX_58535CE29D1F29AF ON hc_demographic_camp_group (u_count)');
        $this->addSql('CREATE INDEX IDX_58535CE22AD9DAB0 ON hc_demographic_camp_group (f_count_leader)');
        $this->addSql('CREATE INDEX IDX_58535CE265E1E15D ON hc_demographic_camp_group (m_count_leader)');
        $this->addSql('CREATE INDEX IDX_58535CE2300AC307 ON hc_demographic_camp_group (u_count_leader)');
        $this->addSql('CREATE INDEX IDX_58535CE2A5840C59 ON hc_demographic_camp_group (group_type)');
        $this->addSql('CREATE TABLE hc_invite (id INT NOT NULL, group_id INT DEFAULT NULL, email VARCHAR(255) NOT NULL, expiration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FC6BB860FE54D947 ON hc_invite (group_id)');
        $this->addSql('CREATE TABLE hc_leader_overview_leader (id INT NOT NULL, widget_leader_overview_id INT DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, name VARCHAR(255) NOT NULL, birthday DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8DD17F374C8AA1E2 ON hc_leader_overview_leader (widget_leader_overview_id)');
        $this->addSql('CREATE INDEX IDX_8DD17F37C7470A42 ON hc_leader_overview_leader (gender)');
        $this->addSql('CREATE INDEX IDX_8DD17F375E237E06 ON hc_leader_overview_leader (name)');
        $this->addSql('CREATE INDEX IDX_8DD17F374709B432 ON hc_leader_overview_leader (birthday)');
        $this->addSql('COMMENT ON COLUMN hc_leader_overview_leader.birthday IS \'(DC2Type:date_immutable)\'');
        $this->addSql('CREATE TABLE hc_leader_overview_qualification (id INT NOT NULL, leader_overview_leader_id INT DEFAULT NULL, qualification_type_id INT DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, event_origin VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8C73B2BC6F7A7E00 ON hc_leader_overview_qualification (leader_overview_leader_id)');
        $this->addSql('CREATE INDEX IDX_8C73B2BC56AF75A6 ON hc_leader_overview_qualification (qualification_type_id)');
        $this->addSql('CREATE INDEX IDX_8C73B2BCA393D2FB ON hc_leader_overview_qualification (state)');
        $this->addSql('COMMENT ON COLUMN hc_leader_overview_qualification.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE hc_widget_demographic_camp (id INT NOT NULL, group_id INT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, camp_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_point_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7EA7F288FE54D947 ON hc_widget_demographic_camp (group_id)');
        $this->addSql('CREATE INDEX data_point_date_idx ON hc_widget_demographic_camp (data_point_date)');
        $this->addSql('CREATE INDEX start_date_idx ON hc_widget_demographic_camp (start_date)');
        $this->addSql('COMMENT ON COLUMN hc_widget_demographic_camp.start_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN hc_widget_demographic_camp.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN hc_widget_demographic_camp.data_point_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE hc_widget_demographic_department (id INT NOT NULL, group_id INT DEFAULT NULL, birthyear INT DEFAULT NULL, m_count INT DEFAULT 0, f_count INT DEFAULT 0, u_count INT DEFAULT 0, m_count_leader INT DEFAULT 0, f_count_leader INT DEFAULT 0, u_count_leader INT DEFAULT 0, group_type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_point_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7DF96E4FE54D947 ON hc_widget_demographic_department (group_id)');
        $this->addSql('CREATE INDEX IDX_7DF96E483F8186E ON hc_widget_demographic_department (birthyear)');
        $this->addSql('CREATE INDEX IDX_7DF96E4C92EFB06 ON hc_widget_demographic_department (m_count)');
        $this->addSql('CREATE INDEX IDX_7DF96E4CB29AFFC ON hc_widget_demographic_department (f_count)');
        $this->addSql('CREATE INDEX IDX_7DF96E49D1F29AF ON hc_widget_demographic_department (u_count)');
        $this->addSql('CREATE INDEX IDX_7DF96E465E1E15D ON hc_widget_demographic_department (m_count_leader)');
        $this->addSql('CREATE INDEX IDX_7DF96E42AD9DAB0 ON hc_widget_demographic_department (f_count_leader)');
        $this->addSql('CREATE INDEX IDX_7DF96E4300AC307 ON hc_widget_demographic_department (u_count_leader)');
        $this->addSql('CREATE INDEX IDX_7DF96E4A5840C59 ON hc_widget_demographic_department (group_type)');
        $this->addSql('CREATE INDEX IDX_7DF96E4EC2BEAC1 ON hc_widget_demographic_department (data_point_date)');
        $this->addSql('COMMENT ON COLUMN hc_widget_demographic_department.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN hc_widget_demographic_department.data_point_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE hc_widget_demographic_entered_left (id INT NOT NULL, group_id INT DEFAULT NULL, new_count_m INT DEFAULT NULL, new_count_leader_m INT DEFAULT NULL, exit_count_m INT DEFAULT NULL, exit_count_leader_m INT DEFAULT NULL, new_count_f INT DEFAULT NULL, new_count_leader_f INT DEFAULT NULL, exit_count_leader_f INT DEFAULT NULL, exit_count_f INT DEFAULT NULL, new_count_u INT DEFAULT NULL, new_count_leader_u INT DEFAULT NULL, exit_count_u INT DEFAULT NULL, exit_count_leader_u INT DEFAULT NULL, group_type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_point_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_503131B9FE54D947 ON hc_widget_demographic_entered_left (group_id)');
        $this->addSql('CREATE INDEX IDX_503131B9B2C0141A ON hc_widget_demographic_entered_left (new_count_m)');
        $this->addSql('CREATE INDEX IDX_503131B97778BB66 ON hc_widget_demographic_entered_left (new_count_leader_m)');
        $this->addSql('CREATE INDEX IDX_503131B97791AA42 ON hc_widget_demographic_entered_left (exit_count_m)');
        $this->addSql('CREATE INDEX IDX_503131B936296FC ON hc_widget_demographic_entered_left (exit_count_leader_m)');
        $this->addSql('CREATE INDEX IDX_503131B92512CD92 ON hc_widget_demographic_entered_left (new_count_f)');
        $this->addSql('CREATE INDEX IDX_503131B9E0AA62EE ON hc_widget_demographic_entered_left (new_count_leader_f)');
        $this->addSql('CREATE INDEX IDX_503131B994B04F74 ON hc_widget_demographic_entered_left (exit_count_leader_f)');
        $this->addSql('CREATE INDEX IDX_503131B9E04373CA ON hc_widget_demographic_entered_left (exit_count_f)');
        $this->addSql('CREATE INDEX IDX_503131B9A1AC8C4C ON hc_widget_demographic_entered_left (new_count_u)');
        $this->addSql('CREATE INDEX IDX_503131B964142330 ON hc_widget_demographic_entered_left (new_count_leader_u)');
        $this->addSql('CREATE INDEX IDX_503131B964FD3214 ON hc_widget_demographic_entered_left (exit_count_u)');
        $this->addSql('CREATE INDEX IDX_503131B9100E0EAA ON hc_widget_demographic_entered_left (exit_count_leader_u)');
        $this->addSql('CREATE INDEX IDX_503131B9A5840C59 ON hc_widget_demographic_entered_left (group_type)');
        $this->addSql('CREATE INDEX IDX_503131B9EC2BEAC1 ON hc_widget_demographic_entered_left (data_point_date)');
        $this->addSql('COMMENT ON COLUMN hc_widget_demographic_entered_left.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN hc_widget_demographic_entered_left.data_point_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE hc_widget_demographic_group (id INT NOT NULL, group_id INT DEFAULT NULL, m_count INT DEFAULT NULL, f_count INT DEFAULT NULL, u_count INT DEFAULT NULL, m_count_leader INT DEFAULT NULL, f_count_leader INT DEFAULT NULL, u_count_leader INT DEFAULT NULL, group_type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_point_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A8C54CCBFE54D947 ON hc_widget_demographic_group (group_id)');
        $this->addSql('CREATE INDEX IDX_A8C54CCBC92EFB06 ON hc_widget_demographic_group (m_count)');
        $this->addSql('CREATE INDEX IDX_A8C54CCBCB29AFFC ON hc_widget_demographic_group (f_count)');
        $this->addSql('CREATE INDEX IDX_A8C54CCB9D1F29AF ON hc_widget_demographic_group (u_count)');
        $this->addSql('CREATE INDEX IDX_A8C54CCB65E1E15D ON hc_widget_demographic_group (m_count_leader)');
        $this->addSql('CREATE INDEX IDX_A8C54CCB2AD9DAB0 ON hc_widget_demographic_group (f_count_leader)');
        $this->addSql('CREATE INDEX IDX_A8C54CCB300AC307 ON hc_widget_demographic_group (u_count_leader)');
        $this->addSql('CREATE INDEX IDX_A8C54CCBA5840C59 ON hc_widget_demographic_group (group_type)');
        $this->addSql('CREATE INDEX IDX_A8C54CCBEC2BEAC1 ON hc_widget_demographic_group (data_point_date)');
        $this->addSql('COMMENT ON COLUMN hc_widget_demographic_group.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN hc_widget_demographic_group.data_point_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE hc_widget_leader_overview (id INT NOT NULL, group_id INT DEFAULT NULL, m_count INT DEFAULT NULL, f_count INT DEFAULT NULL, u_count INT DEFAULT NULL, group_type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_point_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7241D5E9FE54D947 ON hc_widget_leader_overview (group_id)');
        $this->addSql('CREATE INDEX IDX_7241D5E9C92EFB06 ON hc_widget_leader_overview (m_count)');
        $this->addSql('CREATE INDEX IDX_7241D5E9CB29AFFC ON hc_widget_leader_overview (f_count)');
        $this->addSql('CREATE INDEX IDX_7241D5E99D1F29AF ON hc_widget_leader_overview (u_count)');
        $this->addSql('CREATE INDEX IDX_7241D5E9A5840C59 ON hc_widget_leader_overview (group_type)');
        $this->addSql('CREATE INDEX IDX_7241D5E9EC2BEAC1 ON hc_widget_leader_overview (data_point_date)');
        $this->addSql('COMMENT ON COLUMN hc_widget_leader_overview.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN hc_widget_leader_overview.data_point_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE midata_camp_state (id INT NOT NULL, state VARCHAR(255) DEFAULT NULL, de_label VARCHAR(255) DEFAULT NULL, it_label VARCHAR(255) DEFAULT NULL, fr_label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE midata_event (id INT NOT NULL, event_type_id INT DEFAULT NULL, youth_sport_type_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, location VARCHAR(512) DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_702AAD7A401B253C ON midata_event (event_type_id)');
        $this->addSql('CREATE INDEX IDX_702AAD7A61D93469 ON midata_event (youth_sport_type_id)');
        $this->addSql('CREATE INDEX IDX_702AAD7A5E237E06 ON midata_event (name)');
        $this->addSql('CREATE TABLE midata_event_date (id INT NOT NULL, event_id INT DEFAULT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E13DC41771F7E88B ON midata_event_date (event_id)');
        $this->addSql('CREATE INDEX IDX_E13DC417B75363F7 ON midata_event_date (start_at)');
        $this->addSql('CREATE INDEX IDX_E13DC41737D3107C ON midata_event_date (end_at)');
        $this->addSql('COMMENT ON COLUMN midata_event_date.start_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN midata_event_date.end_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE midata_event_group (id INT NOT NULL, event_id INT NOT NULL, group_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E88FAD371F7E88B ON midata_event_group (event_id)');
        $this->addSql('CREATE INDEX IDX_5E88FAD3FE54D947 ON midata_event_group (group_id)');
        $this->addSql('CREATE TABLE midata_event_type (id INT NOT NULL, de_label VARCHAR(255) DEFAULT NULL, it_label VARCHAR(255) DEFAULT NULL, fr_label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE midata_event_type_qualification_type (id INT NOT NULL, event_type_id INT DEFAULT NULL, qualification_type_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B0CD89E7401B253C ON midata_event_type_qualification_type (event_type_id)');
        $this->addSql('CREATE INDEX IDX_B0CD89E756AF75A6 ON midata_event_type_qualification_type (qualification_type_id)');
        $this->addSql('CREATE TABLE midata_group (id INT NOT NULL, parent_group_id INT DEFAULT NULL, group_type_id INT DEFAULT NULL, canton_id INT DEFAULT NULL, canton_name VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2644E31861997596 ON midata_group (parent_group_id)');
        $this->addSql('CREATE INDEX IDX_2644E318434CD89F ON midata_group (group_type_id)');
        $this->addSql('CREATE INDEX IDX_2644E3185E237E06 ON midata_group (name)');
        $this->addSql('CREATE INDEX IDX_2644E3188B8E8428 ON midata_group (created_at)');
        $this->addSql('CREATE INDEX IDX_2644E3184AF38FD1 ON midata_group (deleted_at)');
        $this->addSql('COMMENT ON COLUMN midata_group.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN midata_group.deleted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE midata_group_type (id INT NOT NULL, de_label VARCHAR(255) DEFAULT NULL, it_label VARCHAR(255) DEFAULT NULL, fr_label VARCHAR(255) DEFAULT NULL, group_type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE midata_person (id INT NOT NULL, group_id INT DEFAULT NULL, nickname VARCHAR(255) NOT NULL, pbs_number VARCHAR(255) DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, birthday TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, zip INT DEFAULT NULL, entry_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, leaving_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CCF5FBB8FE54D947 ON midata_person (group_id)');
        $this->addSql('CREATE INDEX IDX_CCF5FBB8A188FE64 ON midata_person (nickname)');
        $this->addSql('CREATE INDEX IDX_CCF5FBB8C7470A42 ON midata_person (gender)');
        $this->addSql('CREATE INDEX IDX_CCF5FBB84709B432 ON midata_person (birthday)');
        $this->addSql('CREATE INDEX IDX_CCF5FBB8EBC4F69 ON midata_person (entry_date)');
        $this->addSql('CREATE INDEX IDX_CCF5FBB8FAD70B3B ON midata_person (leaving_date)');
        $this->addSql('COMMENT ON COLUMN midata_person.birthday IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN midata_person.entry_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN midata_person.leaving_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE midata_person_event (id INT NOT NULL, event_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_51E69FDE71F7E88B ON midata_person_event (event_id)');
        $this->addSql('CREATE INDEX IDX_51E69FDE217BBB47 ON midata_person_event (person_id)');
        $this->addSql('CREATE TABLE midata_person_event_person_event_type (person_event_id INT NOT NULL, person_event_type_id INT NOT NULL, PRIMARY KEY(person_event_id, person_event_type_id))');
        $this->addSql('CREATE INDEX IDX_2073410AE5B14DBC ON midata_person_event_person_event_type (person_event_id)');
        $this->addSql('CREATE INDEX IDX_2073410A489516F1 ON midata_person_event_person_event_type (person_event_type_id)');
        $this->addSql('CREATE TABLE midata_person_event_type (id INT NOT NULL, type VARCHAR(255) NOT NULL, de_label VARCHAR(255) NOT NULL, it_label VARCHAR(255) NOT NULL, fr_label VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE midata_person_qualification (id INT NOT NULL, qualification_type_id INT DEFAULT NULL, person_id INT NOT NULL, event_origin VARCHAR(255) DEFAULT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8974C40356AF75A6 ON midata_person_qualification (qualification_type_id)');
        $this->addSql('CREATE INDEX IDX_8974C403217BBB47 ON midata_person_qualification (person_id)');
        $this->addSql('CREATE INDEX IDX_8974C403B75363F7 ON midata_person_qualification (start_at)');
        $this->addSql('CREATE INDEX IDX_8974C40337D3107C ON midata_person_qualification (end_at)');
        $this->addSql('COMMENT ON COLUMN midata_person_qualification.start_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN midata_person_qualification.end_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE midata_person_role (id INT NOT NULL, group_id INT DEFAULT NULL, person_id INT DEFAULT NULL, role_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AFDC017BFE54D947 ON midata_person_role (group_id)');
        $this->addSql('CREATE INDEX IDX_AFDC017B217BBB47 ON midata_person_role (person_id)');
        $this->addSql('CREATE INDEX IDX_AFDC017BD60322AC ON midata_person_role (role_id)');
        $this->addSql('CREATE INDEX IDX_AFDC017B8B8E8428 ON midata_person_role (created_at)');
        $this->addSql('CREATE INDEX IDX_AFDC017B4AF38FD1 ON midata_person_role (deleted_at)');
        $this->addSql('COMMENT ON COLUMN midata_person_role.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN midata_person_role.deleted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE midata_qualification_type (id INT NOT NULL, validity VARCHAR(255) DEFAULT NULL, de_label VARCHAR(255) DEFAULT NULL, it_label VARCHAR(255) DEFAULT NULL, fr_label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE midata_role (id INT NOT NULL, layer_type VARCHAR(255) DEFAULT NULL, role_type VARCHAR(255) DEFAULT NULL, group_type VARCHAR(255) DEFAULT NULL, de_label VARCHAR(255) DEFAULT NULL, it_label VARCHAR(255) DEFAULT NULL, fr_label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D71A104F326125BD ON midata_role (role_type)');
        $this->addSql('CREATE TABLE midata_youth_sport_type (id INT NOT NULL, type VARCHAR(255) DEFAULT NULL, de_label VARCHAR(255) DEFAULT NULL, it_label VARCHAR(255) DEFAULT NULL, fr_label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE hc_demographic_camp_group ADD CONSTRAINT FK_58535CE26C5AD790 FOREIGN KEY (demographic_camp_id) REFERENCES hc_widget_demographic_camp (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hc_demographic_camp_group ADD CONSTRAINT FK_58535CE2FE54D947 FOREIGN KEY (group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hc_invite ADD CONSTRAINT FK_FC6BB860FE54D947 FOREIGN KEY (group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hc_leader_overview_leader ADD CONSTRAINT FK_8DD17F374C8AA1E2 FOREIGN KEY (widget_leader_overview_id) REFERENCES hc_widget_leader_overview (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hc_leader_overview_qualification ADD CONSTRAINT FK_8C73B2BC6F7A7E00 FOREIGN KEY (leader_overview_leader_id) REFERENCES hc_leader_overview_leader (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hc_leader_overview_qualification ADD CONSTRAINT FK_8C73B2BC56AF75A6 FOREIGN KEY (qualification_type_id) REFERENCES midata_qualification_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hc_widget_demographic_camp ADD CONSTRAINT FK_7EA7F288FE54D947 FOREIGN KEY (group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hc_widget_demographic_department ADD CONSTRAINT FK_7DF96E4FE54D947 FOREIGN KEY (group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hc_widget_demographic_entered_left ADD CONSTRAINT FK_503131B9FE54D947 FOREIGN KEY (group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hc_widget_demographic_group ADD CONSTRAINT FK_A8C54CCBFE54D947 FOREIGN KEY (group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hc_widget_leader_overview ADD CONSTRAINT FK_7241D5E9FE54D947 FOREIGN KEY (group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_event ADD CONSTRAINT FK_702AAD7A401B253C FOREIGN KEY (event_type_id) REFERENCES midata_event_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_event ADD CONSTRAINT FK_702AAD7A61D93469 FOREIGN KEY (youth_sport_type_id) REFERENCES midata_youth_sport_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_event_date ADD CONSTRAINT FK_E13DC41771F7E88B FOREIGN KEY (event_id) REFERENCES midata_event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_event_group ADD CONSTRAINT FK_5E88FAD371F7E88B FOREIGN KEY (event_id) REFERENCES midata_event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_event_group ADD CONSTRAINT FK_5E88FAD3FE54D947 FOREIGN KEY (group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_event_type_qualification_type ADD CONSTRAINT FK_B0CD89E7401B253C FOREIGN KEY (event_type_id) REFERENCES midata_event_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_event_type_qualification_type ADD CONSTRAINT FK_B0CD89E756AF75A6 FOREIGN KEY (qualification_type_id) REFERENCES midata_qualification_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_group ADD CONSTRAINT FK_2644E31861997596 FOREIGN KEY (parent_group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_group ADD CONSTRAINT FK_2644E318434CD89F FOREIGN KEY (group_type_id) REFERENCES midata_group_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_person ADD CONSTRAINT FK_CCF5FBB8FE54D947 FOREIGN KEY (group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_person_event ADD CONSTRAINT FK_51E69FDE71F7E88B FOREIGN KEY (event_id) REFERENCES midata_event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_person_event ADD CONSTRAINT FK_51E69FDE217BBB47 FOREIGN KEY (person_id) REFERENCES midata_person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_person_event_person_event_type ADD CONSTRAINT FK_2073410AE5B14DBC FOREIGN KEY (person_event_id) REFERENCES midata_person_event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_person_event_person_event_type ADD CONSTRAINT FK_2073410A489516F1 FOREIGN KEY (person_event_type_id) REFERENCES midata_person_event_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_person_qualification ADD CONSTRAINT FK_8974C40356AF75A6 FOREIGN KEY (qualification_type_id) REFERENCES midata_qualification_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_person_qualification ADD CONSTRAINT FK_8974C403217BBB47 FOREIGN KEY (person_id) REFERENCES midata_person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_person_role ADD CONSTRAINT FK_AFDC017BFE54D947 FOREIGN KEY (group_id) REFERENCES midata_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_person_role ADD CONSTRAINT FK_AFDC017B217BBB47 FOREIGN KEY (person_id) REFERENCES midata_person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE midata_person_role ADD CONSTRAINT FK_AFDC017BD60322AC FOREIGN KEY (role_id) REFERENCES midata_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE hc_leader_overview_qualification DROP CONSTRAINT FK_8C73B2BC6F7A7E00');
        $this->addSql('ALTER TABLE hc_demographic_camp_group DROP CONSTRAINT FK_58535CE26C5AD790');
        $this->addSql('ALTER TABLE hc_leader_overview_leader DROP CONSTRAINT FK_8DD17F374C8AA1E2');
        $this->addSql('ALTER TABLE midata_event_date DROP CONSTRAINT FK_E13DC41771F7E88B');
        $this->addSql('ALTER TABLE midata_event_group DROP CONSTRAINT FK_5E88FAD371F7E88B');
        $this->addSql('ALTER TABLE midata_person_event DROP CONSTRAINT FK_51E69FDE71F7E88B');
        $this->addSql('ALTER TABLE midata_event DROP CONSTRAINT FK_702AAD7A401B253C');
        $this->addSql('ALTER TABLE midata_event_type_qualification_type DROP CONSTRAINT FK_B0CD89E7401B253C');
        $this->addSql('ALTER TABLE hc_demographic_camp_group DROP CONSTRAINT FK_58535CE2FE54D947');
        $this->addSql('ALTER TABLE hc_invite DROP CONSTRAINT FK_FC6BB860FE54D947');
        $this->addSql('ALTER TABLE hc_widget_demographic_camp DROP CONSTRAINT FK_7EA7F288FE54D947');
        $this->addSql('ALTER TABLE hc_widget_demographic_department DROP CONSTRAINT FK_7DF96E4FE54D947');
        $this->addSql('ALTER TABLE hc_widget_demographic_entered_left DROP CONSTRAINT FK_503131B9FE54D947');
        $this->addSql('ALTER TABLE hc_widget_demographic_group DROP CONSTRAINT FK_A8C54CCBFE54D947');
        $this->addSql('ALTER TABLE hc_widget_leader_overview DROP CONSTRAINT FK_7241D5E9FE54D947');
        $this->addSql('ALTER TABLE midata_event_group DROP CONSTRAINT FK_5E88FAD3FE54D947');
        $this->addSql('ALTER TABLE midata_group DROP CONSTRAINT FK_2644E31861997596');
        $this->addSql('ALTER TABLE midata_person DROP CONSTRAINT FK_CCF5FBB8FE54D947');
        $this->addSql('ALTER TABLE midata_person_role DROP CONSTRAINT FK_AFDC017BFE54D947');
        $this->addSql('ALTER TABLE midata_group DROP CONSTRAINT FK_2644E318434CD89F');
        $this->addSql('ALTER TABLE midata_person_event DROP CONSTRAINT FK_51E69FDE217BBB47');
        $this->addSql('ALTER TABLE midata_person_qualification DROP CONSTRAINT FK_8974C403217BBB47');
        $this->addSql('ALTER TABLE midata_person_role DROP CONSTRAINT FK_AFDC017B217BBB47');
        $this->addSql('ALTER TABLE midata_person_event_person_event_type DROP CONSTRAINT FK_2073410AE5B14DBC');
        $this->addSql('ALTER TABLE midata_person_event_person_event_type DROP CONSTRAINT FK_2073410A489516F1');
        $this->addSql('ALTER TABLE hc_leader_overview_qualification DROP CONSTRAINT FK_8C73B2BC56AF75A6');
        $this->addSql('ALTER TABLE midata_event_type_qualification_type DROP CONSTRAINT FK_B0CD89E756AF75A6');
        $this->addSql('ALTER TABLE midata_person_qualification DROP CONSTRAINT FK_8974C40356AF75A6');
        $this->addSql('ALTER TABLE midata_person_role DROP CONSTRAINT FK_AFDC017BD60322AC');
        $this->addSql('ALTER TABLE midata_event DROP CONSTRAINT FK_702AAD7A61D93469');
        $this->addSql('DROP SEQUENCE hc_demographic_camp_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE hc_invite_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE hc_leader_overview_leader_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE hc_leader_overview_qualification_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE hc_widget_demographic_camp_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE hc_widget_demographic_department_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE hc_widget_demographic_entered_left_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE hc_widget_demographic_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE hc_widget_leader_overview_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_camp_state_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_event_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_event_date_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_event_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_event_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_event_type_qualification_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_group_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_person_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_person_event_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_person_event_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_person_qualification_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_person_role_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_qualification_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_role_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE midata_youth_sport_type_id_seq CASCADE');
        $this->addSql('DROP TABLE hc_demographic_camp_group');
        $this->addSql('DROP TABLE hc_invite');
        $this->addSql('DROP TABLE hc_leader_overview_leader');
        $this->addSql('DROP TABLE hc_leader_overview_qualification');
        $this->addSql('DROP TABLE hc_widget_demographic_camp');
        $this->addSql('DROP TABLE hc_widget_demographic_department');
        $this->addSql('DROP TABLE hc_widget_demographic_entered_left');
        $this->addSql('DROP TABLE hc_widget_demographic_group');
        $this->addSql('DROP TABLE hc_widget_leader_overview');
        $this->addSql('DROP TABLE midata_camp_state');
        $this->addSql('DROP TABLE midata_event');
        $this->addSql('DROP TABLE midata_event_date');
        $this->addSql('DROP TABLE midata_event_group');
        $this->addSql('DROP TABLE midata_event_type');
        $this->addSql('DROP TABLE midata_event_type_qualification_type');
        $this->addSql('DROP TABLE midata_group');
        $this->addSql('DROP TABLE midata_group_type');
        $this->addSql('DROP TABLE midata_person');
        $this->addSql('DROP TABLE midata_person_event');
        $this->addSql('DROP TABLE midata_person_event_person_event_type');
        $this->addSql('DROP TABLE midata_person_event_type');
        $this->addSql('DROP TABLE midata_person_qualification');
        $this->addSql('DROP TABLE midata_person_role');
        $this->addSql('DROP TABLE midata_qualification_type');
        $this->addSql('DROP TABLE midata_role');
        $this->addSql('DROP TABLE midata_youth_sport_type');
    }
}
