name: develop

on:
  workflow_run:
    workflows: [ 'run-tests' ]
    branches: [ develop ]
    types:
      - completed

env:
  DOCKER_REGISTRY_PATH: ghcr.io/digio-ch/pbs-healthcheck-core/healthcheck-core

jobs:
  build-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          file: docker/Dockerfile
          tags: ${{ env.DOCKER_REGISTRY_PATH }}:develop

  dispatch_deploy:
    needs: [ build-dev ]
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger Deployment
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_HC_DISPATCH }}
          repository: digio-ch/pbs-healthcheck-config
          event-type: deploy
          client-payload: '{"ref": "${{ github.ref }}", "app_env": "dev", "target_server": "develop"}'
