name: stage

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

env:
  DOCKER_REGISTRY_PATH: ghcr.io/digio-ch/pbs-healthcheck-core/healthcheck-core

jobs:
  build-stage:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the stage/rc image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          file: docker/Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY_PATH }}:${GITHUB_REF#refs/*/}
            ${{ env.DOCKER_REGISTRY_PATH }}:stage

  dispatch_deploy:
    needs: [ build-stage ]
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger Deployment
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_HC_DISPATCH }}
          repository: digio-ch/pbs-healthcheck-config
          event-type: deploy
          client-payload: '{ "ref": "${{ github.ref }}", "app_env": "stage", "target_server": "stage" }'
